# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 05:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='prof_pics/')),
                ('games_played', models.CharField(max_length=50)),
                ('contact_info', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('slots_available', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash_prize', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('ticket_prize', models.IntegerField(default=0)),
                ('consoles', models.ManyToManyField(to='app.consoles')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='all_Tournaments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tournament'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consoles',
            field=models.ManyToManyField(to='app.consoles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
