# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
