# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190715_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='owner',
        ),
    ]
