# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tournament_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='owner',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
